global:
  params:
    baseline_window_minutes: 3
    feeding_threshold: 10
    feeding_minimum: 10
    tasting_minimum: 0
    tasting_maximum: 10
    feeding_minevents: 1
    tasting_minevents: 1
    samples_per_second: 5
    feeding_event_link_gap: 5
    pi_direction: left
    correct_for_dual_feeding: false
    chamber_size: 2
  experiment_type: two_well
  well_names:
    A: Sucrose
    B: Yeast
  constants:
    min_untransformed_licks_cutoff: 20
    max_med_duration_cutoff: 13.0
    max_events_cutoff: 150000.0
  experimental_design_factors:
    paired:
    - Paired
    - Unpaired
    genotype:
    - Chrim
    - WCS
dfms:
- id: 1
  params:
    pi_direction: left
  chambers:
    1: Paired, WCS
    2: Unpaired, WCS
    3: Paired, Chrim
    4: Unpaired, Chrim
    5: Paired, Chrim
    6: Unpaired, Chrim
- id: 2
  params:
    pi_direction: left
  chambers:
    1: Unpaired, WCS
    2: Paired, WCS
    3: Unpaired, Chrim
    4: Paired, Chrim
    5: Unpaired, Chrim
    6: Paired, Chrim
- id: 3
  params:
    pi_direction: right
  chambers:
    1: Paired, WCS
    2: Unpaired, WCS
    3: Paired, Chrim
    4: Unpaired, Chrim
    5: Paired, Chrim
    6: Unpaired, Chrim
- id: 4
  params:
    pi_direction: right
  chambers:
    1: Unpaired, WCS
    2: Paired, WCS
    3: Unpaired, Chrim
    4: Paired, Chrim
    5: Unpaired, Chrim
    6: Paired, Chrim
- id: 5
  params:
    pi_direction: left
  chambers:
    1: Paired, Chrim
    2: Unpaired, Chrim
    3: Paired, WCS
    4: Unpaired, WCS
    5: Paired, WCS
    6: Unpaired, WCS
- id: 6
  params:
    pi_direction: left
  chambers:
    1: Unpaired, Chrim
    2: Paired, Chrim
    3: Unpaired, WCS
    4: Paired, WCS
    5: Unpaired, WCS
    6: Paired, WCS
- id: 7
  params:
    pi_direction: right
  chambers:
    1: Paired, Chrim
    2: Unpaired, Chrim
    3: Paired, WCS
    4: Unpaired, WCS
    5: Paired, WCS
    6: Unpaired, WCS
- id: 8
  params:
    pi_direction: right
  chambers:
    1: Unpaired, Chrim
    2: Paired, Chrim
    3: Unpaired, WCS
    4: Paired, WCS
    5: Unpaired, WCS
    6: Paired, WCS
