global:
  params:
    baseline_window_minutes: 3
    feeding_threshold: 20
    feeding_minimum: 10
    tasting_minimum: 5
    tasting_maximum: 20
    feeding_minevents: 1
    tasting_minevents: 1
    samples_per_second: 5
    feeding_event_link_gap: 5
    pi_direction: left
    correct_for_dual_feeding: true
    chamber_size: 2
  experiment_type: hedonic
  experimental_design_factors:
    Lights:
    - 'On'
    - 'Off'
    Sucrose:
    - S2
    - S20
dfms:
- id: 2
  params:
    pi_direction: left
  chambers:
    1: On, S2
    2: On, S2
    3: On, S2
    4: On, S2
    5: On, S2
    6: On, S2
- id: 3
  params:
    pi_direction: left
  chambers:
    1: On, S20
    2: On, S20
    3: On, S20
    4: On, S20
    5: On, S20
    6: On, S20
- id: 4
  params:
    pi_direction: right
  chambers:
    1: On, S2
    2: On, S2
    3: On, S2
    4: On, S2
    5: On, S2
    6: On, S2
- id: 5
  params:
    pi_direction: right
  chambers:
    1: On, S20
    2: On, S20
    3: On, S20
    4: On, S20
    5: On, S20
    6: On, S20
- id: 6
  params:
    pi_direction: left
  chambers:
    1: Off, S2
    2: Off, S2
    3: Off, S2
    4: Off, S2
    5: Off, S2
    6: Off, S2
- id: 7
  params:
    pi_direction: left
  chambers:
    1: Off, S20
    2: Off, S20
    3: Off, S20
    4: Off, S20
    5: Off, S20
    6: Off, S20
- id: 9
  params:
    pi_direction: right
  chambers:
    1: Off, S2
    2: Off, S2
    3: Off, S2
    4: Off, S2
    5: Off, S2
    6: Off, S2
- id: 10
  params:
    pi_direction: right
  chambers:
    1: Off, S20
    2: Off, S20
    3: Off, S20
    4: Off, S20
    5: Off, S20
    6: Off, S20
scripts:
- name: batch
  steps:
  - action: load
    end: 0.0
    parallel: true
    start: 0.0
  - action: remove_chambers
    group: Remove_24hr
  - action: basic_analysis
    end: 0.0
    start: 0.0
  - action: load
    end: 360.0
    parallel: true
    start: 0.0
  - action: remove_chambers
    group: Remove_6hr
  - action: feeding_csv
    end: 360.0
    start: 0.0
